import express from 'express';
import cors from 'cors';
import { google } from 'googleapis';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());
app.use(express.json());

// Load Credentials exactly as in your calendar.service.js
// Adjust the path to match wherever your JSON key is located
const KEYFILEPATH = path.join(__dirname, 'support files', 'plv-medsync-10026c433cfb.json');
const CALENDAR_ID = '493ab9c7c42b49f90d556b5289689f1659b06e7decead50b3b3734e7a5adb899@group.calendar.google.com';
const SCOPES = ['https://www.googleapis.com/auth/calendar.events'];

const auth = new google.auth.GoogleAuth({
  keyFile: KEYFILEPATH,
  scopes: SCOPES,
});

const calendar = google.calendar({ version: 'v3', auth });

// ======== GET EVENTS (To populate FullCalendar) ========
app.get('/api/events', async (req, res) => {
  try {
    const { start, end } = req.query; // FullCalendar passes these automatically
    const response = await calendar.events.list({
      calendarId: CALENDAR_ID,
      timeMin: start ? new Date(start).toISOString() : (new Date()).toISOString(),
      timeMax: end ? new Date(end).toISOString() : undefined,
      maxResults: 250,
      singleEvents: true,
      orderBy: 'startTime',
    });

    // Map Google Calendar events to FullCalendar format
    const fcEvents = response.data.items.map((event) => ({
      id: event.id,
      title: event.summary,
      start: event.start.dateTime || event.start.date,
      end: event.end.dateTime || event.end.date,
      backgroundColor: '#0d9488', // Consistent accent
      borderColor: '#0d9488',
    }));

    res.json(fcEvents);
  } catch (error) {
    console.error('Error fetching events:', error.message);
    res.status(500).json({ error: 'Failed to fetch events from Google Calendar' });
  }
});

// ======== CREATE EVENT ========
app.post('/api/events', async (req, res) => {
  try {
    const { patientName, doctorName, startTime, endTime } = req.body;

    const eventData = {
      summary: `[Pending] ${patientName} - ${doctorName}`,
      description: `Automated clinic appointment generated by PLV MedSync.\n\nPatient: ${patientName}\nDoctor: ${doctorName}`,
      start: {
        dateTime: new Date(startTime).toISOString(),
        timeZone: 'Asia/Manila',
      },
      end: {
        dateTime: new Date(endTime).toISOString(),
        timeZone: 'Asia/Manila',
      },
    };

    const response = await calendar.events.insert({
      calendarId: CALENDAR_ID,
      resource: eventData,
    });

    res.status(201).json({ success: true, link: response.data.htmlLink });
  } catch (error) {
    console.error('Error creating event:', error.message);
    res.status(500).json({ error: 'Failed to create event in Google Calendar' });
  }
});

const PORT = 3001;
app.listen(PORT, () => {
  console.log(`🚀 Backend Calendar API running on http://localhost:${PORT}`);
});
