import { google } from 'googleapis';
import path from 'path';
import { fileURLToPath } from 'url';

// ==========================================
// CONFIGURATION
// ==========================================

// To handle __dirname in ES modules:
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Path to your Service Account JSON key file.
// Important: Ensure the JSON file is in the same directory, or update this path to point to it!
const KEYFILEPATH = path.join(__dirname, 'plv-medsync-10026c433cfb.json');

// 2. Your target Google Calendar ID
// As requested, here is the target Calendar ID where events will be plotted
const CALENDAR_ID = '493ab9c7c42b49f90d556b5289689f1659b06e7decead50b3b3734e7a5adb899@group.calendar.google.com';

// The scope needed to create and manage calendar events
const SCOPES = ['https://www.googleapis.com/auth/calendar.events'];

/**
 * Creates a Google Calendar event via Server-to-Server authentication.
 * No user consent required because we are using a Service Account.
 * 
 * @param {string} patientName - Dynamic input for Patient Name
 * @param {string} doctorName - Dynamic input for Doctor Name
 * @param {string|Date} startTime - Event start time (e.g., ISO string representation)
 * @param {string|Date} endTime - Event end time (e.g., ISO string representation)
 * @returns {Promise<object>} - Returns the created Google Calendar event data
 */
export async function createAppointmentEvent(patientName, doctorName, startTime, endTime) {
  try {
    // ---------------------------------------------------------
    // STEP 1 & 2: Load Credentials & Request Access Token
    // ---------------------------------------------------------
    // The GoogleAuth client securely reads the JSON file, handles the JWT 
    // signing process, and automatically requests the temporary Access Token.
    const auth = new google.auth.GoogleAuth({
      keyFile: KEYFILEPATH,
      scopes: SCOPES,
    });

    // Initialize the official Google Calendar API Client
    const calendar = google.calendar({ version: 'v3', auth });

    // ---------------------------------------------------------
    // STEP 3: Construct the Event Payload
    // ---------------------------------------------------------
    const eventSummary = `[Pending] ${patientName} - ${doctorName}`;
    
    // Package event details into Google Calendar's standard JSON format
    const eventData = {
      summary: eventSummary,
      description: `Automated clinic appointment generated by PLV MedSync.\n\nPatient: ${patientName}\nDoctor: ${doctorName}`,
      start: {
        dateTime: new Date(startTime).toISOString(),
        timeZone: 'Asia/Manila', // Using local timezone
      },
      end: {
        dateTime: new Date(endTime).toISOString(),
        timeZone: 'Asia/Manila', // Using local timezone
      },
    };

    // ---------------------------------------------------------
    // STEP 4: Send the Request
    // ---------------------------------------------------------
    const response = await calendar.events.insert({
      calendarId: CALENDAR_ID,
      resource: eventData,
    });

    console.log('✅ Successfully plotted event on calendar! Link:', response.data.htmlLink);
    return response.data;
    
  } catch (error) {
    // Basic Error Handling for API response
    console.error('❌ Failed to create calendar event.');
    
    // Check if the error object contains an API response with details
    if (error.response && error.response.data) {
      console.error('API Error Details:', JSON.stringify(error.response.data.error, null, 2));
    } else {
      console.error('Error Message:', error.message);
    }
    
    throw error;
  }
}
